# Basic Commands    

In [23]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [24]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [25]:
"hello" + " " + "world"

'hello world'

In [26]:
# numpy

In [27]:
import numpy as np

In [46]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [29]:
x.ndim

1

In [30]:
y = np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
y.ndim

2

In [32]:
y.dtype

dtype('int64')

In [33]:
np.array([[1,2,3,4],[5.9,6,7,8]]).dtype

dtype('float64')

In [39]:
x.sum()

np.int64(15)

### reshape

In [43]:
x.shape

(5,)

In [48]:
# x = np.array([1,2,3,4,5])
print("beginning x: \n", x)
x_reshaped = x.reshape((2,3))
print("Reshaped x:\n", x_reshaped)

beginning x: 
 [1 2 3 4 5 6]
Reshaped x:
 [[1 2 3]
 [4 5 6]]


In [51]:
x_reshaped[1]

array([4, 5, 6])

In [55]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [57]:
x**2

array([ 1,  4,  9, 16, 25, 36])

### Touple

 - cant be reassigned

In [58]:
my_touple = (1,2,3,4)

In [65]:
my_touple[0] = 5

TypeError: 'tuple' object does not support item assignment

- Generating random variables from numpy

In [61]:
np.random.normal(size=50)

array([-1.21585325e+00, -3.65612611e-01, -3.47439343e-01,  1.46815517e+00,
       -1.15652178e+00,  1.56161351e-01,  1.23618565e-01, -3.79211508e-01,
       -4.47482940e-01,  1.73506712e+00,  1.69755424e+00,  4.69303694e-01,
        1.17788203e-01,  1.25412805e+00,  1.38954396e+00,  1.17744541e+00,
       -1.21287759e+00,  6.79256355e-01,  8.19938156e-01, -1.20700013e+00,
        9.20613971e-01, -2.85806444e-01, -3.10458365e-01, -1.10211406e-01,
        1.89899768e+00,  1.85146130e+00,  5.03042051e-01, -1.36126024e+00,
        1.90055154e+00,  6.62973385e-02, -3.74184399e-01, -4.01591041e-01,
       -1.23854569e+00,  5.35615001e-01,  9.04541123e-04, -7.11931011e-01,
       -2.91803991e-01, -1.13201287e+00,  1.76958679e+00,  1.23038530e+00,
       -1.45807615e+00, -1.80714756e-01, -3.40303113e-01, -7.35764789e-01,
       -2.38759708e-01,  8.78159981e-01, -5.78071233e-01, -2.57715199e-01,
       -8.44236015e-01,  5.14353296e-01])

In [63]:
x_reshaped.shape, x_reshaped.ndim, x_reshaped.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [64]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]
